using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyAttack : MonoBehaviour
{
    private void Update()
    {
        
    }

    private void SwitchSkills()
    {
        // SWITCH PARA LLAMAR A LOS DISTINTOS ATAQUES, (VA VARIANDO CADA CIERTO TIEMPO EL ATAQUE A INSTANCIAR)
        // PARA LLAMAR CADA ATAQUE SE USA INTERFACE// BUSCAR UN OBJETO POR TIPO Y ACCERDER A SU INTEFACE
        //PARA EL ATAQUE DE BARRA USAR SCRIPT DE DISPARO
    }


    //EL METODO ES UNA RUTINA QUE SIRVE PARA ACTIVAR Y RANDOMIZAR EL ATAQUE, USAR UN METODO ABSTRACTO
    //CADA CLASE HIJA INTEGRA SU LOGICA DE CADA ATAQUE




    //HACER ESTA UNA CLASE PADRE, Y QUE CADA ATAQUE SEA SU CALSE HIJA, ANTES DE INSTANCIAR UN ATAQUE SE VERIFICA SI YA HAY OTRO EN LA ESCENA
}
